# Generated by Django 2.2.17 on 2023-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.TextField()),
                ('Date1', models.DateField()),
                ('Signature1', models.ImageField(upload_to='signatures/')),
                ('Sender Email', models.EmailField(max_length=254)),
                ('Receiver Name', models.TextField()),
                ('Receiver Email', models.EmailField(max_length=254)),
                ('signing_url', models.URLField(blank=True)),
            ],
        ),
    ]
