# Generated by Django 2.2.17 on 2023-04-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Name1',
            field=models.CharField(max_length=200),
        ),
    ]
