# Generated by Django 2.2.17 on 2023-04-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_remove_contract_signing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Receiver Name',
            field=models.CharField(max_length=200),
        ),
    ]
