# Generated by Django 2.2.17 on 2023-05-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0004_auto_20230412_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Receiver Email',
            new_name='recipient_email',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Name1',
            new_name='recipient_name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Sender Email',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Receiver Name',
            new_name='sender_name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Date1',
            new_name='sign_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='Signature1',
        ),
    ]
