# Generated by Django 2.2.17 on 2023-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0005_auto_20230507_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(default='/staticfiles/Document.pdf', upload_to=''),
        ),
    ]
