# Generated by Django 2.2.17 on 2023-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0007_auto_20230510_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(default='Document.pdf', upload_to=''),
        ),
    ]
