# Generated by Django 2.2.17 on 2023-05-10 06:32

from django.db import migrations, models
import esign.models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0008_auto_20230510_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(default=esign.models.get_default_document, upload_to='contracts'),
        ),
    ]
