# Generated by Django 2.2.17 on 2023-05-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0010_auto_20230510_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sign_date',
        ),
    ]
